name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql:latest
        ports:
          - 5432:5432
        env:
          - POSTGRESQL_USERNAME=admin
          - POSTGRESQL_PASSWORD=admin
          - POSTGRESQL_DATABASE=gymapi

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://admin:admin@localhost:5432/gymapi?schema=public"
